/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arrays;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arch
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Exercise4Part1 = new javax.swing.JLabel();
        jButton_doExercise4Part1 = new javax.swing.JButton();
        jLabel_inputCaptionNExercise4Part1 = new javax.swing.JLabel();
        jTextField_inputNExercise4Part1 = new javax.swing.JTextField();
        jLabel_inputCaptionKExercise4Part1 = new javax.swing.JLabel();
        jTextField_inputKExercise4Part1 = new javax.swing.JTextField();
        jLabel_outputArrayCaptionExercise4Part1 = new javax.swing.JLabel();
        jLabel_outputResultExercise4Part1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_exercise29Part1 = new javax.swing.JLabel();
        jLabel_outputMinValueExercise29Part1 = new javax.swing.JLabel();
        jButton_doExercise29Part1 = new javax.swing.JButton();
        jLabel_outputArrayExercise29Part1 = new javax.swing.JLabel();
        jLabel_outputIndexMinValueExercise29Part1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_exercise54Part1 = new javax.swing.JLabel();
        jButton_doExercise54Part1 = new javax.swing.JButton();
        jLabel_outputArrayExercise54Part1 = new javax.swing.JLabel();
        jLabel_outputResultExercise54Part1 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel_exercise4Part2 = new javax.swing.JLabel();
        jLabel_outputNExercise4Part2 = new javax.swing.JLabel();
        jLabel_outputSumExercise4Part2 = new javax.swing.JLabel();
        jButton_doExercise4Part2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_outputArrayExercise4Part2 = new javax.swing.JTable();
        jTextField_inputColumnsExercise4Part2 = new javax.swing.JTextField();
        jTextField_inputRowsExercise4Part2 = new javax.swing.JTextField();
        jLabel_inputCaptionColumnsExercise4Part2 = new javax.swing.JLabel();
        jLabel_inputCaptionRowsExercise4Part2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel_exercise29Part2 = new javax.swing.JLabel();
        jLabel_outputCaptionExercise29Part2 = new javax.swing.JLabel();
        jButton_doExercise29Part2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_outputResultExercise29Part2 = new javax.swing.JTable();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel_exercise4Part3 = new javax.swing.JLabel();
        jButton_doExercise4Part3 = new javax.swing.JButton();
        jTextField_inputExercise4Part3 = new javax.swing.JTextField();
        jLabel_outputResultExercise4Part3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel_exercise29Part3 = new javax.swing.JLabel();
        jTextField_inputExercise29Part3 = new javax.swing.JTextField();
        jLabel_outputResultExercise29Part3 = new javax.swing.JLabel();
        jButton_doExercise29Part3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel_exercise54Part3 = new javax.swing.JLabel();
        jTextField_inputExercise54Part3 = new javax.swing.JTextField();
        jButton_doExercise54Part3 = new javax.swing.JButton();
        jLabel_outputLetersExercise54Part3 = new javax.swing.JLabel();
        jLabel_outputDigitsExercise54Part3 = new javax.swing.JLabel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel_exercise4Part4 = new javax.swing.JLabel();
        jButton_doExercise4Part4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_outputExercise4Part4 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_exitButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Exercise4Part1.setText("<html>Задан одномерный массив А[1..20]. Найти минимальный элемент<br/> среди элементов массива с n-го по k-й (n и k вводятся с клавиатуры)</html>");

        jButton_doExercise4Part1.setText("Выполнить");
        jButton_doExercise4Part1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise4Part1ActionPerformed(evt);
            }
        });

        jLabel_inputCaptionNExercise4Part1.setText("n:");

        jLabel_inputCaptionKExercise4Part1.setText("k: ");

        jLabel_outputArrayCaptionExercise4Part1.setText("Массив; ");

        jLabel_outputResultExercise4Part1.setText("Результат: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Exercise4Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton_doExercise4Part1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_inputCaptionKExercise4Part1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_inputKExercise4Part1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_inputCaptionNExercise4Part1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_inputNExercise4Part1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_outputArrayCaptionExercise4Part1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_outputResultExercise4Part1)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Exercise4Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_inputCaptionNExercise4Part1)
                    .addComponent(jTextField_inputNExercise4Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_inputKExercise4Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_inputCaptionKExercise4Part1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_doExercise4Part1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_outputArrayCaptionExercise4Part1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_outputResultExercise4Part1)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("4", jPanel1);

        jLabel_exercise29Part1.setText("<html>Задан одномерный массив A[1..20].<br/> Найти минимальный элемент среди элементов, стоящих на четных позициях и его номер.</html>");

        jLabel_outputMinValueExercise29Part1.setText("Минимальное значение: ");

        jButton_doExercise29Part1.setText("Выполнить");
        jButton_doExercise29Part1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise29Part1ActionPerformed(evt);
            }
        });

        jLabel_outputArrayExercise29Part1.setText("Массив: ");

        jLabel_outputIndexMinValueExercise29Part1.setText("Индекс минимального значения: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise29Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_outputMinValueExercise29Part1)
                    .addComponent(jButton_doExercise29Part1)
                    .addComponent(jLabel_outputIndexMinValueExercise29Part1)
                    .addComponent(jLabel_outputArrayExercise29Part1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise29Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputMinValueExercise29Part1)
                .addGap(9, 9, 9)
                .addComponent(jLabel_outputIndexMinValueExercise29Part1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_outputArrayExercise29Part1)
                .addGap(18, 18, 18)
                .addComponent(jButton_doExercise29Part1)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("29", jPanel2);

        jLabel_exercise54Part1.setText("<html>В массиве хранится информация о количестве побед, одержанных 20<br/> футбольными командами. С помощью датчика случайных чисел заполнить массив целыми значениями, лежащими<br/> в диапазоне от 0 до 5 включительно. Определить номера команд, одержавших более 3-х побед.</html>");

        jButton_doExercise54Part1.setText("Выполнить");
        jButton_doExercise54Part1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise54Part1ActionPerformed(evt);
            }
        });

        jLabel_outputArrayExercise54Part1.setText("Массив: ");

        jLabel_outputResultExercise54Part1.setText("Результат: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise54Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_doExercise54Part1)
                    .addComponent(jLabel_outputArrayExercise54Part1)
                    .addComponent(jLabel_outputResultExercise54Part1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise54Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputArrayExercise54Part1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_outputResultExercise54Part1)
                .addGap(40, 40, 40)
                .addComponent(jButton_doExercise54Part1)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("54", jPanel4);

        jTabbedPane1.addTab("Раздел 1", jTabbedPane2);

        jLabel_exercise4Part2.setText("В двумерном массиве найти сумму всех тех элементов, сумма индексов которых равна n.");

        jLabel_outputNExercise4Part2.setText("N: ");

        jLabel_outputSumExercise4Part2.setText("Сумма: ");

        jButton_doExercise4Part2.setText("Выполнить");
        jButton_doExercise4Part2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise4Part2ActionPerformed(evt);
            }
        });

        jTable_outputArrayExercise4Part2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(jTable_outputArrayExercise4Part2);

        jLabel_inputCaptionColumnsExercise4Part2.setText("Столбцов");

        jLabel_inputCaptionRowsExercise4Part2.setText("Строк");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_exercise4Part2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel_outputSumExercise4Part2)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(244, 244, 244)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton_doExercise4Part2)
                                                .addComponent(jLabel_inputCaptionRowsExercise4Part2)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel_inputCaptionColumnsExercise4Part2)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel_outputNExercise4Part2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_inputRowsExercise4Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_inputColumnsExercise4Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGap(170, 170, 170))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise4Part2)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_outputNExercise4Part2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_inputColumnsExercise4Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_inputCaptionColumnsExercise4Part2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_outputSumExercise4Part2)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_inputCaptionRowsExercise4Part2)
                        .addComponent(jTextField_inputRowsExercise4Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jButton_doExercise4Part2)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("4", jPanel5);

        jLabel_exercise29Part2.setText("<html>Вывести на экран матрицу 5х5, элементами которой являются целые случайные <br/> числа из интервала [-19,49]. Найти сумму четных элементов каждого столбца.</html>");

        jLabel_outputCaptionExercise29Part2.setText("Результат: ");

        jButton_doExercise29Part2.setText("Выполнить");
        jButton_doExercise29Part2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise29Part2ActionPerformed(evt);
            }
        });

        jTable_outputResultExercise29Part2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable_outputResultExercise29Part2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise29Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton_doExercise29Part2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_outputCaptionExercise29Part2))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise29Part2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_doExercise29Part2)
                .addGap(17, 17, 17)
                .addComponent(jLabel_outputCaptionExercise29Part2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("29", jPanel6);

        jTabbedPane1.addTab("Раздел 2", jTabbedPane5);

        jLabel_exercise4Part3.setText("Определить, какой процент слов в тексте содержит букву О (слова разделены пробелами).");

        jButton_doExercise4Part3.setText("Выполнить");
        jButton_doExercise4Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise4Part3ActionPerformed(evt);
            }
        });

        jLabel_outputResultExercise4Part3.setText("Результат");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton_doExercise4Part3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_exercise4Part3)
                            .addComponent(jTextField_inputExercise4Part3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_outputResultExercise4Part3))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel_exercise4Part3)
                .addGap(41, 41, 41)
                .addComponent(jButton_doExercise4Part3)
                .addGap(34, 34, 34)
                .addComponent(jTextField_inputExercise4Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel_outputResultExercise4Part3)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("4", jPanel7);

        jLabel_exercise29Part3.setText("Подсчитать количество цифр во введенной строке, кратных 3");

        jLabel_outputResultExercise29Part3.setText("Результат: ");

        jButton_doExercise29Part3.setText("Выполнить");
        jButton_doExercise29Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise29Part3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_exercise29Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_inputExercise29Part3))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel_outputResultExercise29Part3)
                        .addGap(98, 98, 98)
                        .addComponent(jButton_doExercise29Part3)))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel_exercise29Part3)
                .addGap(28, 28, 28)
                .addComponent(jTextField_inputExercise29Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_outputResultExercise29Part3)
                    .addComponent(jButton_doExercise29Part3))
                .addContainerGap(478, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("29", jPanel8);

        jLabel_exercise54Part3.setText("Создать процедуру, определяющую количество букв и количество цифр во введенной строке.");

        jButton_doExercise54Part3.setText("Выполнить");
        jButton_doExercise54Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise54Part3ActionPerformed(evt);
            }
        });

        jLabel_outputLetersExercise54Part3.setText("Букв: ");

        jLabel_outputDigitsExercise54Part3.setText("Цифр: ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_outputLetersExercise54Part3)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_exercise54Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_inputExercise54Part3))
                            .addComponent(jLabel_outputDigitsExercise54Part3)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton_doExercise54Part3)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel_exercise54Part3)
                .addGap(34, 34, 34)
                .addComponent(jTextField_inputExercise54Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel_outputLetersExercise54Part3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputDigitsExercise54Part3)
                .addGap(3, 3, 3)
                .addComponent(jButton_doExercise54Part3)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("54", jPanel9);

        jTabbedPane1.addTab("Раздел 3", jTabbedPane6);

        jLabel_exercise4Part4.setText("Протабулировать функцию y=ex + e-x для -2<=x<=2 с шагом 0.2, записать данные в файл и просмотреть данные из файла.");

        jButton_doExercise4Part4.setText("Выполнить");
        jButton_doExercise4Part4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise4Part4ActionPerformed(evt);
            }
        });

        jTable_outputExercise4Part4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "x", "y = ex + e -x"
            }
        ));
        jScrollPane3.setViewportView(jTable_outputExercise4Part4);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_exercise4Part4))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton_doExercise4Part4))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise4Part4)
                .addGap(70, 70, 70)
                .addComponent(jButton_doExercise4Part4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("4", jPanel10);

        jTabbedPane1.addTab("Раздел 4", jTabbedPane7);

        jMenu1.setText("File");

        jMenuItem_exitButton.setText("Выход");
        jMenuItem_exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exitButtonActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_exitButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("help");

        jMenuItem2.setText("О разработчике");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_doExercise4Part1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise4Part1ActionPerformed
        int[] A = new int[20]; // Создание нового массива A
        A = Generate.generateArray(A, 100, 0);

        // Получаем n и k с текстовых полей. parseInt -- пытается считать число из строки
        int n = Integer.parseInt(jTextField_inputNExercise4Part1.getText());
        int k = Integer.parseInt(jTextField_inputKExercise4Part1.getText());

        // Поиск самого минимального значения в массиве
        // Создаем переменную, которая будет хранить самое минмальное значение в массиве A
        // Изначально присваиваем этой переменной самое максимальное значение
        int min = Integer.MAX_VALUE;
        for (int i = n; i < k + 1; i++) { // Проходимся по массиву
            // Math.min вернет самое маленькое число из min и A[i].
            // Таким образом у нас в мин всегда будет самое минимальное число
            min = Math.min(min, A[i]);
        }

        // выводим на экран результат и массив
        jLabel_outputArrayCaptionExercise4Part1.setText("Минимальное: " + Integer.toString(min));
        jLabel_outputResultExercise4Part1.setText("Массив: " + Arrays.toString(A));
    }//GEN-LAST:event_jButton_doExercise4Part1ActionPerformed

    private void jButton_doExercise29Part1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise29Part1ActionPerformed
        int[] A = new int[20]; // Создание нового массива A

        A = Generate.generateArray(A, 100, 0);

        // Поиск самого минимального значения в массиве
        // Создаем переменную, которая будет хранить самое минмальное значение в массиве A
        // Изначально присваиваем этой переменной самое максимальное значение
        int min = Integer.MAX_VALUE;
        int min_i = -1; // Эта переменная хранит индекс самого минимального числа в массиве
        for (int i = 0; i < A.length; i++) {
            if (i % 2 == 0) { // Определяем четность индекса
                // Math.min вернет самое маленькое число из min и A[i].
                // Таким образом у нас в мин всегда будет самое минимальное число
                if (A[i] < min) {
                    min = Math.min(min, A[i]);
                    min_i = i; // Записываем индекс нового самого минимального элемента
                }
            }
        }

        // Выводим результат
        jLabel_outputMinValueExercise29Part1.setText("Минимальное значение: " + Integer.toString(min));
        jLabel_outputIndexMinValueExercise29Part1.setText("Индекс минимального значения: " + Integer.toString(min_i));
        jLabel_outputArrayExercise29Part1.setText("Массив" + Arrays.toString(A));
    }//GEN-LAST:event_jButton_doExercise29Part1ActionPerformed

    private void jButton_doExercise54Part1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise54Part1ActionPerformed
        int[] A = new int[20]; // Создание нового массива A
        // Создаем новый список элементов. Список это то же самое, что и массив, 
        // только без ограниченний на размер
        ArrayList<Integer> result = new ArrayList<Integer>();

        A = Generate.generateArray(A, 6, 0);

        for (int i = 0; i < A.length; i++) {
            if (A[i] > 3) { // Если елемент больше 3
                result.add(i+1); // Тогда добавляем позицию элемента в результат
            }
        }

        // Выводим результат
        jLabel_outputArrayExercise54Part1.setText("Массив: " + Arrays.toString(A));
        jLabel_outputResultExercise54Part1.setText("Результат: " + Arrays.toString(result.toArray()));
    }//GEN-LAST:event_jButton_doExercise54Part1ActionPerformed

    private void jButton_doExercise4Part2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise4Part2ActionPerformed
        int columns = Integer.parseInt(jTextField_inputColumnsExercise4Part2.getText()); // Количество столбцов
        int rows = Integer.parseInt(jTextField_inputRowsExercise4Part2.getText()); // Количество строк

        int[][] A = new int[rows][columns]; // Двумерный массив(матрица)
        int sum = 0; // Хранит сумму
        int n = 0;
        try {
            n = Integer.parseInt(jTextField1.getText());
        } catch (Exception e) {
            System.out.println("Введите в N число");
        }

        A = Generate.generateArray(A, 68, -19);

        for (int j = 0; j < A[0].length; j++) {
            for (int i = 0; i < A.length; i++) {
                if (i + j == n) {
                    sum += A[i][j];
                }
            }
        }

        // Выводим результат
        ShowOnTable.showOnTable(A, jTable_outputArrayExercise4Part2);
        jLabel_outputNExercise4Part2.setText("n: " + Integer.toString(n));
        jLabel_outputSumExercise4Part2.setText("Сумма:" + Integer.toString(sum));
    }//GEN-LAST:event_jButton_doExercise4Part2ActionPerformed

    private void jButton_doExercise29Part2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise29Part2ActionPerformed
        int[][] A = new int[5][5]; // Двумерный массив(матрица)
        int[] sum = new int[5];

        A = Generate.generateArray(A, 68, -19);

        // Поиск суммы четных элементов столбоц
        for (int j = 0; j < A[0].length; j++) {
            for (int i = 0; i < A.length; i++) {
                if (i % 2 == 0) {
                    sum[j] += A[i][j];
                }
            }
        }

        // Выводим результат
        ShowOnTable.showOnTable(A, jTable_outputResultExercise29Part2);
        jLabel_outputCaptionExercise29Part2.setText("Результат: " + Arrays.toString(sum));
    }//GEN-LAST:event_jButton_doExercise29Part2ActionPerformed

    private void jButton_doExercise4Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise4Part3ActionPerformed
        String input = jTextField_inputExercise4Part3.getText(); // Получение строки
        String[] words = input.split(" "); // Деление строки на строки в местах, где стоял пробел
        double count = 0; // Счетчик слов с о

        for (String word : words) {
            // Если(слово в нижнем регистре содержит о)
            if (word.contains("О")) {
                count += 1.0;
            }
        }

        double result = count / words.length * 100;

        // Выводим результат
        jLabel_outputResultExercise4Part3.setText("Результат: " + Double.toString(result));
    }//GEN-LAST:event_jButton_doExercise4Part3ActionPerformed

    private void jButton_doExercise29Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise29Part3ActionPerformed
        String input = jTextField_inputExercise29Part3.getText(); // Получение ввода 
        int result = 0; // результат

        for (int i = 0; i < input.length(); i++) {
            String c = String.valueOf(input.charAt(i)); // Получение символа строки
            try { // Конструкция отлавливающая ошибки(исключения)
                int number = Integer.parseInt(c); // Получени числа из строки
                // Если число кратно трем
                if (number % 3 == 0) {
                    result++;
                }
            } catch (Exception e) { // Если произошла какая либо-ошибка
                continue; // То пропускаем эту итерацию
            }
        }

        // Выводим результат
        jLabel_outputResultExercise29Part3.setText("Результат:" + Integer.toString(result));
    }//GEN-LAST:event_jButton_doExercise29Part3ActionPerformed

    private void jButton_doExercise54Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise54Part3ActionPerformed
        String input = jTextField_inputExercise54Part3.getText(); // Получения ввода
        int countWords = 0; // Количество слов
        int countDigits = 0; // Количество цифр

        for (int i = 0; i < input.length(); i++) {
            String c = String.valueOf(input.charAt(i)); // Получение символа строки
            if (c.matches("[A-zА-я]")) // Если символ - буква
            {
                countWords++;
            } else if (c.matches("[0-9]")) // Если символ - цифра
            {
                countDigits++;
            }
        }

        // Выводим результат
        jLabel_outputLetersExercise54Part3.setText("Букв: " + Integer.toString(countWords));
        jLabel_outputDigitsExercise54Part3.setText("Цифр: " + Integer.toString(countDigits));
    }//GEN-LAST:event_jButton_doExercise54Part3ActionPerformed

    private void jButton_doExercise4Part4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise4Part4ActionPerformed
        String path_of = "C:\\Users\\Student\\Desktop\\a.txt"; // Путь, до создаваемого файла
        String to_write = ""; // Вспомогательная строка используемая для более удобной записи в файл (к записи)

        for (double x = -2; x <= 2; x += 0.2) { // Проходимся по всем x от -2 до 2 с шагом 0.2
            Double y = Math.E * x + Math.E - x; // Вычисляем y при каждом x
            to_write += Double.toString(x) + " " + Double.toString(y) + "\n"; // Добавляем к записи новую пару x и y
        }
        // Создаем файл и записываем все из to_write. Передаем путь до файла, путь до папки, в которой будет храниться файл, имя файла, и что записываем
        createAndWriteFile(path_of, "/tmp", "file.txt", to_write);

        // Считываем данные из файла
        List<String> fileLines = readFromFile(path_of); // Получаем все строки файла
        double[][] tableXY = new double[fileLines.size()][2]; // Объявляем массив, который хранит x и y

        for (int i = 0; i < fileLines.size(); i++) { // проходимся по строкам
            String[] splitedLine = fileLines.get(i).split(" "); // Разделяем строки в местах пробела
            tableXY[i][0] = Double.parseDouble(splitedLine[0]); // Записываем x
            tableXY[i][1] = Double.parseDouble(splitedLine[1]); // Записываем y
        }

        // Выводим результат
        ShowOnTable.showOnTable(tableXY, jTable_outputExercise4Part4);
    }//GEN-LAST:event_jButton_doExercise4Part4ActionPerformed

    private void jMenuItem_exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exitButtonActionPerformed
        System.exit(0); // Выход из приложения со статусом "ВСЕ ОК"
    }//GEN-LAST:event_jMenuItem_exitButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(jMenu1, "Разработчик: Настя");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static Path createFile(String path_of, String pathOfDirectory, String name) {
        Path path = Path.of(path_of); // Пытаеться получить путь до создаваемого файла для проверки его существования
        Path directory = Path.of(pathOfDirectory); // Хранит путь до директории
        if (!Files.exists(path)) { // Проверяем существует ли файл
            try {
                path = Files.createFile(directory.resolve(name)); // Создаем файл
            } catch (IOException ex) { // Отлавливает ошибки и если находит то записывает в логгер
                java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        return path;
    }

    public static void writeFile(Path path, String to_write) {
        try {
            Files.writeString(path, to_write, StandardCharsets.UTF_8); // Записываем строку в файл
        } catch (IOException ex) { // Отлавливает ошибки и если находит то записывает в логгер
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public static void createAndWriteFile(String path_of, String path_of_directory, String name, String to_write) {
        Path path = createFile(path_of, path_of_directory, name); // Переменная которая хранит путь до новосозданного файла
        if (path != null) { // Путь существует
            writeFile(path, to_write); // записываем в него информацию из to_write
        }
    }

    public static List<String> readFromFile(String path_of) {
        Path path = Paths.get(path_of); // Получаем путь до файла
        List<String> result = null; // Будет хранить результат

        try {
            result = Files.readAllLines(path); // Считываем все строки из файла
        } catch (IOException ex) { // Отлавливает ошибки и если находит то записывает в логгер
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_doExercise29Part1;
    private javax.swing.JButton jButton_doExercise29Part2;
    private javax.swing.JButton jButton_doExercise29Part3;
    private javax.swing.JButton jButton_doExercise4Part1;
    private javax.swing.JButton jButton_doExercise4Part2;
    private javax.swing.JButton jButton_doExercise4Part3;
    private javax.swing.JButton jButton_doExercise4Part4;
    private javax.swing.JButton jButton_doExercise54Part1;
    private javax.swing.JButton jButton_doExercise54Part3;
    private javax.swing.JLabel jLabel_Exercise4Part1;
    private javax.swing.JLabel jLabel_exercise29Part1;
    private javax.swing.JLabel jLabel_exercise29Part2;
    private javax.swing.JLabel jLabel_exercise29Part3;
    private javax.swing.JLabel jLabel_exercise4Part2;
    private javax.swing.JLabel jLabel_exercise4Part3;
    private javax.swing.JLabel jLabel_exercise4Part4;
    private javax.swing.JLabel jLabel_exercise54Part1;
    private javax.swing.JLabel jLabel_exercise54Part3;
    private javax.swing.JLabel jLabel_inputCaptionColumnsExercise4Part2;
    private javax.swing.JLabel jLabel_inputCaptionKExercise4Part1;
    private javax.swing.JLabel jLabel_inputCaptionNExercise4Part1;
    private javax.swing.JLabel jLabel_inputCaptionRowsExercise4Part2;
    private javax.swing.JLabel jLabel_outputArrayCaptionExercise4Part1;
    private javax.swing.JLabel jLabel_outputArrayExercise29Part1;
    private javax.swing.JLabel jLabel_outputArrayExercise54Part1;
    private javax.swing.JLabel jLabel_outputCaptionExercise29Part2;
    private javax.swing.JLabel jLabel_outputDigitsExercise54Part3;
    private javax.swing.JLabel jLabel_outputIndexMinValueExercise29Part1;
    private javax.swing.JLabel jLabel_outputLetersExercise54Part3;
    private javax.swing.JLabel jLabel_outputMinValueExercise29Part1;
    private javax.swing.JLabel jLabel_outputNExercise4Part2;
    private javax.swing.JLabel jLabel_outputResultExercise29Part3;
    private javax.swing.JLabel jLabel_outputResultExercise4Part1;
    private javax.swing.JLabel jLabel_outputResultExercise4Part3;
    private javax.swing.JLabel jLabel_outputResultExercise54Part1;
    private javax.swing.JLabel jLabel_outputSumExercise4Part2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable jTable_outputArrayExercise4Part2;
    private javax.swing.JTable jTable_outputExercise4Part4;
    private javax.swing.JTable jTable_outputResultExercise29Part2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_inputColumnsExercise4Part2;
    private javax.swing.JTextField jTextField_inputExercise29Part3;
    private javax.swing.JTextField jTextField_inputExercise4Part3;
    private javax.swing.JTextField jTextField_inputExercise54Part3;
    private javax.swing.JTextField jTextField_inputKExercise4Part1;
    private javax.swing.JTextField jTextField_inputNExercise4Part1;
    private javax.swing.JTextField jTextField_inputRowsExercise4Part2;
    // End of variables declaration//GEN-END:variables
}

class Student {

    private String name;
    private String last_name;
    private String gender;
    private int age;

    public Student(String name, String last_name, String gender, int age) {
        this.name = name;
        this.last_name = last_name;
        this.gender = gender;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public String getGender() {
        return gender;
    }

    public int getAge() {
        return age;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

}
